# Generated by Django 4.2.7 on 2023-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
