# Generated by Django 4.2.7 on 2023-11-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='industry',
            field=models.CharField(max_length=20),
        ),
    ]
