# Generated by Django 4.2.7 on 2023-11-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_portfolio_client_alter_portfolio_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='service',
        ),
    ]
